app.controller "HeatMapCtrl",
  ["$scope", "$state",  "$interval", "$window", "$meteor", "_util", "uiGmapGoogleMapApi", "uiGmapIsReady",
  ($scope, $state, $interval,  $window, $meteor, _util, uiGmapGoogleMapApi, uiGmapIsReady) ->
    map = undefined
    uiGmapIsReady.promise(1).then (instances) ->
      instances.forEach (inst) ->
        map = inst.map
        HeatLayer layer
        return
      return
    layer = undefined

    HeatLayer = (heatLayer) ->
      pointarray = undefined
      houseData = []
      pointArray = new google.maps.MVCArray houseData
      $meteor
        .call("getUserData")
        .then(
          (result) ->
            result.forEach (record) ->
              houseData.push { location:new google.maps.LatLng( record.lat, record.lng ), weight: 0.5 }
            heatmap = new google.maps.visualization.HeatmapLayer { data: pointArray, map: map, radius: 15 }
          , 
          (error) ->
            console.log(error)
        )
      return

    $scope.heatLayerCallback = (layer) ->
      layer = layer
      #set the heat layers backend data
      return

    $scope.map =
      center:
        latitude: 52.5125000
        longitude: 6.094440
      zoom: 13
      options: {
        disableDefaultUI: true
        zoomControl: true
        zoomControlOptions: {
          style: google.maps.ZoomControlStyle.SMALL
        }
      }
    $scope.showHeat = true
    $scope.locationCompanies = []
    uiGmapGoogleMapApi.then (maps) ->
      map = maps
      return
 ]

# ---
# generated by js2coffee 2.1.0