app.controller "HeatMapCtrl",
  ["$scope", "$state",  "$interval", "$window", "$meteor", "_util", "uiGmapGoogleMapApi", "uiGmapIsReady",
  ($scope, $state, $interval,  $window, $meteor, _util, uiGmapGoogleMapApi, uiGmapIsReady) ->
    map = undefined
    uiGmapIsReady.promise(1).then (instances) ->
      instances.forEach (inst) ->
        map = inst.map
        MockHeatLayer layer
        return
      return
    layer = undefined

    MockHeatLayer = (heatLayer) ->
      pointarray = undefined
      houseData = []
      pointArray = new (google.maps.MVCArray)(houseData)
      #heatLayer.setData(pointArray);
      $meteor
      .call("getUserData")
      .then((result) ->
        console.log "XXX", result
        result.forEach (record) ->
          console.log(record.lat)
          houseData.push({location:new google.maps.LatLng(record.lng, record.lat), weight:1})
        heatmap = new (google.maps.visualization.HeatmapLayer)(data: pointArray)
        heatmap.setMap map
        heatmap.set 'radius', 20
      , (error) ->
        console.log(error)
      )
  #      gradient = [
  #        'rgba(0, 255, 255, 0)'
  #        'rgba(0, 255, 255, 1)'
  #        'rgba(0, 191, 255, 1)'
  #        'rgba(0, 127, 255, 1)'
  #        'rgba(0, 63, 255, 1)'
  #        'rgba(0, 0, 255, 1)'
  #        'rgba(0, 0, 223, 1)'
  #        'rgba(0, 0, 191, 1)'
  #        'rgba(0, 0, 159, 1)'
  #        'rgba(0, 0, 127, 1)'
  #        'rgba(63, 0, 91, 1)'
  #        'rgba(127, 0, 63, 1)'
  #        'rgba(191, 0, 31, 1)'
  #        'rgba(255, 0, 0, 1)'
  #      ]
  #      heatmap.set 'gradient', gradient
      return

    $scope.heatLayerCallback = (layer) ->
      layer = layer
      #set the heat layers backend data
      return

    $scope.map =
      center:
        latitude: 52.465527
        longitude: 5.565698
      zoom: 8
    $scope.showHeat = true
    $scope.locationCompanies = []
    uiGmapGoogleMapApi.then (maps) ->
      map = maps
      return
 ]

# ---
# generated by js2coffee 2.1.0